WebApplicationDemo/Models/Employee.cs
namespace WebApplicationDemo.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public double Salary { get; set; }
    }
}

WebApplicationDemo/Models/EmployeeVal.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplicationDemo.Models
{
    public class EmployeeVal
    {
        [Required(ErrorMessage = "id is required")]
        [MaxLength(20)]
        [MinLength(5)]
        public string? EmpId { get; set; }

        [Required(ErrorMessage = "name is required")]
        [MaxLength(40)]
        [MinLength(3)]
        public string? EmpName { get; set; }

        [Required(ErrorMessage = "email is required")]
        [DataType(DataType.EmailAddress)]
        public string? Email { get; set; }

        //[Required(ErrorMessage = "department is required")]
        //[DataType(DataType.Department)]
        //public string? Dept { get; set; }

        [Required(ErrorMessage = "age is required")]
        [Range(minimum: 18, maximum: 58)]
        public int Age { get; set; }

        [Required(ErrorMessage = "password is required")]
        [DataType(DataType.Password)]
        public string? Password { get; set; }


        [Required(ErrorMessage = "confirm password is required")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "password does not match")]
        public string? ConfirmPassword { get; set; }


        [Required(ErrorMessage = "salary is required")]
        public int Salary { get; set; }
    }
}

WebApplicationDemo/Models/EmployeeValController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplicationDemo.Models
{
    public class EmployeeValController : Controller
    {
        public IActionResult RegisterEmp()
        {
            return View();
        }
        [HttpPost]
        public IActionResult RegisterEmp(EmployeeVal emp)
        {
            return View("DisplayEmpVal");
        }
    }
}

WebApplicationDemo/Models/ErrorViewModel.cs
namespace WebApplicationDemo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplicationDemo/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplicationDemo.Models
{
    public class User
    {
        [Required(ErrorMessage ="name is required")]
        [MaxLength(40)]
        [MinLength(3)]
        public string? UserName { get; set; }

        [Required(ErrorMessage = "email is required")]
        [DataType(DataType.EmailAddress)]
        public string? Email { get; set; }

        [Required(ErrorMessage = "age is required")]
        [Range(minimum: 18, maximum: 58)]
        public int Age { get; set; }

        [Required(ErrorMessage = "password is required")]
        [DataType(DataType.Password)]
        public string? Password { get; set; }


        [Required(ErrorMessage = "confirm password is required")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "password does not match")]
        public string? ConfirmPassword { get; set; } // ? is to allow null

    }
}

WebApplicationDemo/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplicationDemo.Models;

namespace WebApplicationDemo.Controllers
{
    public class EmployeeController : Controller
    {
        public IActionResult List()
        {
            TempData["message"] = "Hello from employee controller";
            TempData.Keep("message");
            ViewData["message"] = "Hello from controller";
            List<string> names = new List<string>() { "John", "Nick", "Joe", "Barbara", "Justin", "Kiara" };
            ViewData["names"] = names;
            ViewBag.Names = names;
        
            List<Employee> employees = new List<Employee>() { 
                new Employee{Id=1,Name="John",Department="Development",Salary=50000 },
                new Employee{Id=2,Name="Selena",Department="Testing",Salary=40000 },
                new Employee{Id=3,Name="Nick",Department="Tech Support",Salary=20000 },
                new Employee{Id=4,Name="Joe",Department="Medical",Salary=70000 },
                new Employee{Id=5,Name="Justin",Department="Law",Salary=30000 }
            };
            ViewData["emplist"] = employees;
            ViewBag.Employees = employees;
            return View();
        }
    }
}

WebApplicationDemo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplicationDemo.Models;

namespace WebApplicationDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplicationDemo/Controllers/PersonController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApplicationDemo.Controllers
{
    //[HttpGet]  -> It is optional
    public class PersonController : Controller
    {
        public IActionResult PersonalDetails()
        {
            List<string> cities = new List<string>() { "Pune", "Banglore", "Mumbai", "Delhi", "Indore","Hyderabad" };
            ViewData["cities"] = new SelectList(cities);
            return View();
        }
        [HttpPost]
        public IActionResult PersonalDetails(IFormCollection form) //model binding
        {
            ViewBag.Name = form["personname"];
            ViewBag.Email = form["email"];
            ViewBag.City = form["cities"];
            return View("Display");
        }
           
    }
}

WebApplicationDemo/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApplicationDemo.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult StudentDetails()
        {
            List<string> branch = new List<string>() { "IT", "CS", "EE", "Civil", "ME", "EC" };
            ViewData["branch"] = new SelectList(branch);
            return View();
        }
        [HttpPost]
        public IActionResult StudentDetails(IFormCollection form) 
        {
            ViewBag.RollNo = form["rollno"];
            ViewBag.Name = form["name"];
            ViewBag.Branch = form["branch"];
            ViewBag.Year = form["year"];
            return View("DisplayDetails");
        }
    }
}

WebApplicationDemo/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplicationDemo.Models;

namespace WebApplicationDemo.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Register(User user)
        {
            return View();
        }
    }
}

WebApplicationDemo/Views/Employee/List.cshtml
@{
    ViewData["Title"] = "List";
}

<h2>Employee List</h2>
<p>
    @ViewData["message"]
</p>
<div>
    <ol>
        @foreach(string s in (IEnumerable<string>)ViewData["names"])
        {
            <li>
                @s
            </li>
        }
    </ol>
</div>

<div>
    <table class="table table-bordered">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Department</th>
            <th>Salary</th>
        </tr>
        @foreach(Employee e in (IEnumerable<Employee>)ViewData["emplist"])
        {
            <tr>
                <td>@e.Id</td>
                <td>@e.Name</td>
                <td>@e.Department</td>
                <td>@e.Salary</td>
            </tr>
        }
    </table>
</div>

<div>
    <table class="table table-bordered">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Department</th>
            <th>Salary</th>
        </tr>
        @if(ViewData["emplist"]!=null)
        {
            @foreach (Employee e in ViewBag.Employees)
            {
                <tr>
                    <td>@e.Id</td>
                    <td>@e.Name</td>
                    <td>@e.Department</td>
                    <td>@e.Salary</td>
                </tr>
            }
        }  
    </table>
</div>

WebApplicationDemo/Views/EmployeeVal/DisplayEmpVal.cshtml
@{
    ViewData["Title"] = "DisplayEmpVal";
}

<h1>Display Employee Details</h1>
<p>Hello, Emp Id @ViewBag.Id</p>
<p>Your Name @ViewBag.Name</p>
<p>Your Email @ViewBag.Email</p>
<p>Your Age @ViewBag.Age</p>
<p>You're Salary @ViewBag.Salary</p>

WebApplicationDemo/Views/EmployeeVal/RegisterEmp.cshtml
@model WebApplicationDemo.Models.EmployeeVal

@{
    ViewData["Title"] = "RegisterEmp";
}

<h1>RegisterEmp</h1>

<h4>EmployeeVal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="RegisterEmp">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EmpId" class="control-label"></label>
                <input asp-for="EmpId" class="form-control" />
                <span asp-validation-for="EmpId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmpName" class="control-label"></label>
                <input asp-for="EmpName" class="form-control" />
                <span asp-validation-for="EmpName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword" class="control-label"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplicationDemo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplicationDemo/Views/Person/Display.cshtml
@{
    ViewData["Title"] = "Display";
}

<h1>Your Details</h1>
<p>Hello, @ViewBag.Name</p>
<p>Your Email Id @ViewBag.Email</p>
<p>You are from @ViewBag.City</p>

WebApplicationDemo/Views/Person/PersonalDetails.cshtml
@{
    ViewData["Title"] = "PersonalDetails";
}

<h1>PersonalDetails</h1>
<form asp-action="PersonalDetails">
    <table class="table">
        <tr>
            <td>Enter your Name : </td>
            <td>
                <input type="text" name="personname" id="personname"/>
            </td>
        </tr>
        <tr>
            <td>Enter your Email : </td>
            <td>@Html.TextBox("email")</td>
        </tr>
        <tr>
            <td>Select city : </td>
            <td>@Html.DropDownList("cities")</td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Save" class="btn btn-primary"/>
            </td>
        </tr>
    </table>
</form>

WebApplicationDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplicationDemo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplicationDemo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Employee List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Personal Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">User Validation</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmployeeVal" asp-action="RegisterEmp">Employee Validation</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplicationDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplicationDemo/Views/Student/DisplayDetails.cshtml
@{
    ViewData["Title"] = "DisplayDetails";
}
<h1>Your Details</h1>
<p>Hello, Roll No @ViewBag.RollNo</p>
<p>Your Name @ViewBag.Name</p>
<p>Your Branch @ViewBag.Branch</p>
<p>You are in @ViewBag.Year</p>

WebApplicationDemo/Views/Student/StudentDetails.cshtml
@{
    ViewData["Title"] = "StudentDetails";
}

<h1>StudentDetails</h1>
<form asp-action="StudentDetails">
    <table class="table">
        <tr>
            <td>Enter your RollNo : </td>
            <td>
                <input type="text" name="rollno" id="rollno" />
            </td>
        </tr>
        <tr>
            <td>Enter your Name : </td>
            <td>
                <input type="text" name="name" id="name" />
            </td>
        </tr>
        <tr>
            <td>Select Branch : </td>
            <td>@Html.DropDownList("branch")</td>
        </tr>
        <tr>
            <td>Select Year : </td>
            <td>
                <input type="radio" name="year" value="1" id="y1" /> 1st Year
                <input type="radio" name="year" value="2" id="y2" /> 2nd Year
                <input type="radio" name="year" value="3" id="y3" /> 3rd Year
                <input type="radio" name="year" value="4" id="y4" /> 4th Year
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Save" class="btn btn-primary" />
            </td>
        </tr>
    </table>
</form>

WebApplicationDemo/Views/User/Register.cshtml
@model WebApplicationDemo.Models.User

@{
    ViewData["Title"] = "Register";
}

<h1>Register</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword" class="control-label"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}